import search from "../Assets/search.svg";
import cart from "../Assets/cart.svg";
import discount from "../Assets/discount.svg";
import help from "../Assets/help.svg";
import signin from "../Assets/signin.svg";
import searchHover from "../Assets/searchHover.svg";
import cartHover from "../Assets/cartHover.svg";
import discountHover from "../Assets/discountHover.svg";
import helpHover from "../Assets/helpHover.svg";
import signinHover from "../Assets/signinHover.svg";

export const NavigationOptions = [
  {
    name: "Search",
    icon: search,
    hoverIcon: searchHover,
    hasBadge: false,
    badgeName: "",
  },
  {
    name: "Offers",
    icon: discount,
    hoverIcon: discountHover,
    hasBadge: false,
    badgeName: "NEW",
  },
  {
    name: "Help",
    icon: help,
    hoverIcon: helpHover,
    hasBadge: false,
    badgeName: "",
  },
  {
    name: "Sign In",
    icon: signin,
    hoverIcon: signinHover,
    hasBadge: false,
    badgeName: "",
  },
  {
    name: "Cart",
    icon: cart,
    hoverIcon: cartHover,
    hasBadge: false,
    badgeName: "",
  },
];

export const DishesHomePage = [
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1675667625/PC_Creative%20refresh/Biryani_2.png",
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1675667625/PC_Creative%20refresh/North_Indian_4.png",
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1675667626/PC_Creative%20refresh/South_Indian_4.png",
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1674029845/PC_Creative%20refresh/3D_bau/banners_new/Burger.png",
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1674029856/PC_Creative%20refresh/3D_bau/banners_new/Pizza.png",
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1674029848/PC_Creative%20refresh/3D_bau/banners_new/Chinese.png",
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1674029858/PC_Creative%20refresh/3D_bau/banners_new/Pure_Veg.png",
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1674029850/PC_Creative%20refresh/3D_bau/banners_new/Dosa.png",
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1674029858/PC_Creative%20refresh/3D_bau/banners_new/Rolls.png",
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1674029851/PC_Creative%20refresh/3D_bau/banners_new/Ice_Creams.png",
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1674029853/PC_Creative%20refresh/3D_bau/banners_new/Paratha.png",
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1674029844/PC_Creative%20refresh/3D_bau/banners_new/Chole_Bature.png",
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1674029845/PC_Creative%20refresh/3D_bau/banners_new/Cakes.png",
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1674029855/PC_Creative%20refresh/3D_bau/banners_new/Noodles.png",
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1674029859/PC_Creative%20refresh/3D_bau/banners_new/Salad.png",
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1674029847/PC_Creative%20refresh/3D_bau/banners_new/Pastry.png",
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1674029846/PC_Creative%20refresh/3D_bau/banners_new/Idli.png",
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1674029853/PC_Creative%20refresh/3D_bau/banners_new/Kebabs.png",
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1674029859/PC_Creative%20refresh/3D_bau/banners_new/Shawarma.png",
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1674029849/PC_Creative%20refresh/3D_bau/banners_new/Pancake.png",
];

export const TopRestaurantChainList = [
  {
    link: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/5a148e63e9c54942e37627da1aa156be",
    title: "Wow! Momo",
    rating: 4.2,
    deliveryTime: "25-30 mins",
    foodStyle: "Tibetan Healthy Food, Asian,...",
    location: "Jayanagar",
  },
  {
    link: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/e996wruqpmrrrqglp7hs",
    title: "Wow! Momo",
    rating: 4.2,
    deliveryTime: "25-30 mins",
    foodStyle: "Tibetan Healthy Food, Asian,...",
    location: "Jayanagar",
  },
  {
    link: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/psjafovxcvdkmxcgsq76",
    title: "Wow! Momo",
    rating: 4.2,
    deliveryTime: "25-30 mins",
    foodStyle: "Tibetan Healthy Food, Asian,...",
    location: "Jayanagar",
  },
  {
    link: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/405645b3118d83e89db4c65361e43733",
    title: "Wow! Momo",
    rating: 4.2,
    deliveryTime: "25-30 mins",
    foodStyle: "Tibetan Healthy Food, Asian,...",
    location: "Jayanagar",
  },
  {
    link: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/e33e1d3ba7d6b2bb0d45e1001b731fcf",
    title: "Wow! Momo",
    rating: 4.2,
    deliveryTime: "25-30 mins",
    foodStyle: "Tibetan Healthy Food, Asian,...",
    location: "Jayanagar",
  },
  {
    link: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/f01666ac73626461d7455d9c24005cd4",
    title: "Wow! Momo",
    rating: 4.2,
    deliveryTime: "25-30 mins",
    foodStyle: "Tibetan Healthy Food, Asian,...",
    location: "Jayanagar",
  },
  {
    link: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/195876a3181ef63f76e45e3a7b49b585",
    title: "Wow! Momo",
    rating: 4.2,
    deliveryTime: "25-30 mins",
    foodStyle: "Tibetan Healthy Food, Asian,...",
    location: "Jayanagar",
  },
  {
    link: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/b2edbc28b7b8219d6e0a9c049ce06658",
    title: "Wow! Momo",
    rating: 4.2,
    deliveryTime: "25-30 mins",
    foodStyle: "Tibetan Healthy Food, Asian,...",
    location: "Jayanagar",
  },
  {
    link: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/cd832b6167eb9f88aeb1ccdebf38d942",
    title: "Wow! Momo",
    rating: 4.2,
    deliveryTime: "25-30 mins",
    foodStyle: "Tibetan Healthy Food, Asian,...",
    location: "Jayanagar",
  },
  {
    link: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/p57honbbzdgf7tyt2vay",
    title: "Wow! Momo",
    rating: 4.2,
    deliveryTime: "25-30 mins",
    foodStyle: "Tibetan Healthy Food, Asian,...",
    location: "Jayanagar",
  },
  {
    link: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/n85lmofooiw4birffqne",
    title: "Wow! Momo",
    rating: 4.2,
    deliveryTime: "25-30 mins",
    foodStyle: "Tibetan Healthy Food, Asian,...",
    location: "Jayanagar",
  },
  {
    link: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/win6uczwtszg007suegg",
    title: "Wow! Momo",
    rating: 4.2,
    deliveryTime: "25-30 mins",
    foodStyle: "Tibetan Healthy Food, Asian,...",
    location: "Jayanagar",
  },
  {
    link: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/b8ys30ttkzmiypgdj4qz",
    title: "Wow! Momo",
    rating: 4.2,
    deliveryTime: "25-30 mins",
    foodStyle: "Tibetan Healthy Food, Asian,...",
    location: "Jayanagar",
  },
  {
    link: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/63178e3e64d503a479f2a2048a474552",
    title: "Wow! Momo",
    rating: 4.2,
    deliveryTime: "25-30 mins",
    foodStyle: "Tibetan Healthy Food, Asian,...",
    location: "Jayanagar",
  },
  {
    link: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/gxe4mn4ubw70yx3flyar",
    title: "Wow! Momo",
    rating: 4.2,
    deliveryTime: "25-30 mins",
    foodStyle: "Tibetan Healthy Food, Asian,...",
    location: "Jayanagar",
  },
  {
    link: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/af33b81798b11deba338e94b7585d348",
    title: "Wow! Momo",
    rating: 4.2,
    deliveryTime: "25-30 mins",
    foodStyle: "Tibetan Healthy Food, Asian,...",
    location: "Jayanagar",
  },
  {
    link: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/2b4f62d606d1b2bfba9ba9e5386fabb7",
    title: "Wow! Momo",
    rating: 4.2,
    deliveryTime: "25-30 mins",
    foodStyle: "Tibetan Healthy Food, Asian,...",
    location: "Jayanagar",
  },
  {
    link: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/bb6049fae59b8a2413a9177eb0338b49",
    title: "Wow! Momo",
    rating: 4.2,
    deliveryTime: "25-30 mins",
    foodStyle: "Tibetan Healthy Food, Asian,...",
    location: "Jayanagar",
  },
  {
    link: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/4edcfc66d91018d69894941ebb3c8d16",
    title: "Wow! Momo",
    rating: 4.2,
    deliveryTime: "25-30 mins",
    foodStyle: "Tibetan Healthy Food, Asian,...",
    location: "Jayanagar",
  },
  {
    link: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/6e04be27387483a7c00444f8e8241108",
    title: "Wow! Momo",
    rating: 4.2,
    deliveryTime: "25-30 mins",
    foodStyle: "Tibetan Healthy Food, Asian,...",
    location: "Jayanagar",
  },
];
